* intro to tensors
* Getting info from tensors
* Manipulating tensors
* tensors and numpy
* using GPU or TPU
* using tf.function to improve the speed of basic functions

In [ ]:
import tensorflow as tf
print(tf.__version__)

2.15.0


In [ ]:
# creating tensor with tf.constant()
scalar = tf.constant(9)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=9>

In [ ]:
#to check the dimensions of the tensor
scalar.ndim

0

In [ ]:
vector  = tf.constant([[1,2],
                       [1,2]])
vector

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [1, 2]], dtype=int32)>

In [ ]:
vector.ndim

2

* scalar is a single number
* vector is a number with direction
* matrix is a 2-d array of numbers
* tensor n dimensional array of numbers (n any dimensions, 0 dimension is a scalar and more than 0 is a vector)

**Now creating tensors with tf.variable()**

In [ ]:
unchangeable = tf.constant([12,3])
changeable = tf.Variable([12,3])
unchangeable, changeable

(<tf.Tensor: shape=(2,), dtype=int32, numpy=array([12,  3], dtype=int32)>,
 <tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([12,  3], dtype=int32)>)

In [ ]:
#lets change the elements of the tensor using .assign()
changeable[0].assign(9)
#we cant do the same thing with unchangable tensor i.e (tf.constant())

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([9, 3], dtype=int32)>

**Creating Random tensors**

In [ ]:


random1 = tf.random.Generator.from_seed(32)
random1 = random1.normal(shape=(2,2))
random1

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[0.7901182 , 1.585549  ],
       [0.4356279 , 0.23645182]], dtype=float32)>

In [ ]:
random2 = tf.random.Generator.from_seed(32)
random2 = random2.normal(shape=(2,2))
random2

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[0.7901182 , 1.585549  ],
       [0.4356279 , 0.23645182]], dtype=float32)>

In [ ]:
random1 == random2

<tf.Tensor: shape=(2, 2), dtype=bool, numpy=
array([[ True,  True],
       [ True,  True]])>

**Shuffle the order of tensors**

Shuffling will be done when there is same data continuously for certain amount
for example if theres same breed dog image in first 10000 images the algo only learns the characteristics of that one particular dog until it reaches the 10k+ so there the shuffling comes into picture

In [ ]:
not_shuffled = tf.constant([[1,2,4],
                            [2,3,4],
                            [24,12,3]])
not_shuffled

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 1,  2,  4],
       [ 2,  3,  4],
       [24, 12,  3]], dtype=int32)>

In [ ]:
tf.random.set_seed(32)
tf.random.shuffle(not_shuffled)


<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[24, 12,  3],
       [ 1,  2,  4],
       [ 2,  3,  4]], dtype=int32)>

Other ways to create Tensors

In [ ]:
tf.ones(shape=(10,2))

<tf.Tensor: shape=(10, 2), dtype=float32, numpy=
array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]], dtype=float32)>

In [ ]:
tf.zeros(shape=(5,5))

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]], dtype=float32)>

Can turn numpy arrays to tensors the only difference between

them is Tensors runs faster on the GPU.otherwise both are same

---



In [ ]:

import numpy as np
array = np.arange(1,37,dtype=np.int32)
array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36], dtype=int32)

In [ ]:
#to convert the abpve array to tensor
tf.constant(array,shape=(3,6,2)) #2=dimensions, 3 = rows , 4=columns

<tf.Tensor: shape=(3, 6, 2), dtype=int32, numpy=
array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8],
        [ 9, 10],
        [11, 12]],

       [[13, 14],
        [15, 16],
        [17, 18],
        [19, 20],
        [21, 22],
        [23, 24]],

       [[25, 26],
        [27, 28],
        [29, 30],
        [31, 32],
        [33, 34],
        [35, 36]]], dtype=int32)>

The above matrix can be done by just multiplying the D*R*C

3x6x2 = the numpy array

In [ ]:
array2 = np.array([[2,2,1],
                   [3,5,6],
                   [52,2,5]])
array2

array([[ 2,  2,  1],
       [ 3,  5,  6],
       [52,  2,  5]])

In [ ]:
tensor2 = tf.constant(array2)
tensor2

<tf.Tensor: shape=(3, 3), dtype=int64, numpy=
array([[ 2,  2,  1],
       [ 3,  5,  6],
       [52,  2,  5]])>

In [ ]:
tf.random.set_seed(32)
tf.random.shuffle(tensor2)

<tf.Tensor: shape=(3, 3), dtype=int64, numpy=
array([[52,  2,  5],
       [ 2,  2,  1],
       [ 3,  5,  6]])>

**Getting information from tensors**

When dealing with tensors should aware of these attributes
* Rank
* size
* shape
* Axis or dimension

In [ ]:
#create a rank 4 tensor 4dimensions
Rank_4tensor = tf.zeros(shape=[2,3,4,5])
Rank_4tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
Rank_4tensor.shape , Rank_4tensor.ndim, tf.size(Rank_4tensor)
#size = 2*3*4*5 = 120

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

**INDEXING TENSORS**

as we do to python lists


In [ ]:
#get the first 2 elements of each dimension

In [ ]:
Rank_4tensor[:2,:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [ ]:
Rank_4tensor[:3,:3,:3,:3]

<tf.Tensor: shape=(2, 3, 3, 3), dtype=float32, numpy=
array([[[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]]], dtype=float32)>

In [ ]:
example_list = [1,2,3,4]
example_list[:2]
example_list[-1]

4

In [ ]:
#to get the last item of the tensor
random_ten = tf.constant([[1, 2],
                          [3,4]])

In [ ]:
random_ten.ndim , random_ten[-1]

(2, <tf.Tensor: shape=(2,), dtype=int32, numpy=array([3, 4], dtype=int32)>)

In [ ]:
new_ten = random_ten[...,tf.newaxis]

In [ ]:
new_ten

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[1],
        [2]],

       [[3],
        [4]]], dtype=int32)>

In [ ]:
tf.expand_dims(random_ten,axis=-1) #other way to change the dimension

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[1],
        [2]],

       [[3],
        [4]]], dtype=int32)>

In [ ]:
tf.expand_dims(random_ten,axis=0) #the extra dimension will be declared (middle, begining or end)

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[1, 2],
        [3, 4]]], dtype=int32)>

**Manipulating tensors with Basic operators**

+,-,\ ,*

In [ ]:
tensor = tf.constant([[10,5],[3,1]])

In [ ]:
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  5],
       [ 3,  1]], dtype=int32)>

In [ ]:
tensor+12 #(adds 10 to all the elements in the tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[22, 17],
       [15, 13]], dtype=int32)>

In [ ]:
tensor=tensor+12

In [ ]:
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[22, 17],
       [15, 13]], dtype=int32)>

Sub(-)

In [ ]:
tensor-10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[12,  7],
       [ 5,  3]], dtype=int32)>

**Instead of python operators can use TF builtin functions ***

In [ ]:
tf.multiply(tensor,2)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[44, 34],
       [30, 26]], dtype=int32)>

In [ ]:
tf.add(tensor,3)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[25, 20],
       [18, 16]], dtype=int32)>

In [ ]:
tf.subtract(tensor,2)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 15],
       [13, 11]], dtype=int32)>

In [ ]:
matA = tf.constant([[1,2,3],
                    [4,5,6]])
matB = tf.constant([2,
                    4,
                    34],
                    )

**Matrix Multiplication**

In [ ]:
matA*matB

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[  2,   8, 102],
       [  8,  20, 204]], dtype=int32)>

In [ ]:
matA % matB

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [0, 1, 6]], dtype=int32)>

In [ ]:
#create a tensor (3,2)
Mat = tf.constant([[2,4]])

In [ ]:
matA & matB

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[0, 0, 2],
       [0, 4, 2]], dtype=int32)>

In [ ]:
tf.multiply(matA,matB)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[  2,   8, 102],
       [  8,  20, 204]], dtype=int32)>

***dot product**
*  matrix mul is also refferred as Dotproduct

   tf.matmul()
   
   tf.tensordot()

In [ ]:
#TO perform the dot product it requires matA or matB should be transposed

In [ ]:
matA

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>

In [ ]:
matB

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([ 2,  4, 34], dtype=int32)>

In [ ]:
a = tf.constant([[1,2],
                 [4,6],
                 [12,1]])
b= tf.constant([[1,6],
               [21,1],
               [12,2]])

In [ ]:
b.shape

TensorShape([3, 2])

In [ ]:
tf.tensordot(tf.transpose(b),a,axes=1) #Reshaping B matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[229, 140],
       [ 34,  20]], dtype=int32)>

In [ ]:
tf.transpose(b)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 1, 21, 12],
       [ 6,  1,  2]], dtype=int32)>

In [ ]:
tf.transpose(a)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 1,  4, 12],
       [ 2,  6,  1]], dtype=int32)>

In [ ]:
tf.tensordot(tf.transpose(a),b,axes=1) #reshaping the a matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[229,  34],
       [140,  20]], dtype=int32)>

In [ ]:
tf.tensordot(tf.reshape(a,shape=[2,3]),b,axes=1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 91,  16],
       [270,  50]], dtype=int32)>

In [ ]:
tf.matmul(b,tf.reshape(a,shape=[2,3],))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[37, 74, 10],
       [27, 54, 85],
       [24, 48, 50]], dtype=int32)>

**Changing the datatypes of the tennsor**

In [ ]:
c = tf.constant([1.2,2,3])

In [ ]:
c.dtype

tf.float32

In [ ]:
d = tf.constant([1,2,3])

In [ ]:
d.dtype

tf.int32

In [ ]:
#TO change the int32 or float32 to 16bits

In [ ]:
s = tf.cast(d,dtype=tf.int16)

In [ ]:
s.dtype #CHANGED DTYPE

tf.int16

In [ ]:
i = tf.cast(c,dtype=tf.float16) #CHANGED DTYPE
i.dtype

tf.float16

In [ ]:
n = tf.cast(i,dtype=tf.int16) #FLoat16 to int16

In [ ]:
n.dtype

tf.int16

**Aggregating Tensors**

In [ ]:
D = tf.constant([2,1])

In [ ]:
tf.abs(D) # abs() use to remove the negatives in the array

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 1], dtype=int32)>

* min
* max
* mean
* median
* sum

In [ ]:
tf.reduce_mean(D)

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [ ]:
E = tf.constant([[1,2,4],
                 [2,5,0]])

In [ ]:
tf.reduce_mean(E)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [ ]:
tf.reduce_min(E,axis=0)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 0], dtype=int32)>

In [ ]:
tf.reduce_sum(E) #adds all the elements

<tf.Tensor: shape=(), dtype=int32, numpy=14>

In [ ]:
import tensorflow_probability as tfp


In [ ]:
tfp.stats.variance(E,sample_axis=0)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([0, 2, 4], dtype=int32)>

In [ ]:
E.dtype

tf.int32

**Positional maximum and minimum**
* To check at which index in a tensor the max or min value is present

In [ ]:
tf.random.set_seed(32)
T = tf.random.uniform(shape=[25])
T

<tf.Tensor: shape=(25,), dtype=float32, numpy=
array([0.54520595, 0.13372338, 0.45232666, 0.15582252, 0.9621073 ,
       0.8151462 , 0.4068215 , 0.9565903 , 0.5532354 , 0.44936454,
       0.01469815, 0.86204493, 0.12014258, 0.91072273, 0.00848019,
       0.62772846, 0.8167286 , 0.98235905, 0.06410611, 0.17873585,
       0.07358396, 0.95524645, 0.5906956 , 0.3774085 , 0.9427308 ],
      dtype=float32)>

In [ ]:
tf.argmax(T) #index values

<tf.Tensor: shape=(), dtype=int64, numpy=17>

In [ ]:
#largest value  position
T[tf.argmax(T)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.98235905>

In [ ]:
T[tf.argmin(T)] #smallest

<tf.Tensor: shape=(), dtype=float32, numpy=0.008480191>

**Squeezing a tensor**
* removing all single dimensional tensors

In [ ]:
tf.random.set_seed(32)
t = tf.constant(tf.random.uniform(shape=[12]),shape=[1,1,1,1,12])
t

<tf.Tensor: shape=(1, 1, 1, 1, 12), dtype=float32, numpy=
array([[[[[0.54520595, 0.13372338, 0.45232666, 0.15582252, 0.9621073 ,
           0.8151462 , 0.4068215 , 0.9565903 , 0.5532354 , 0.44936454,
           0.01469815, 0.86204493]]]]], dtype=float32)>

In [ ]:
t_sq = tf.squeeze(t)
t_sq

<tf.Tensor: shape=(12,), dtype=float32, numpy=
array([0.54520595, 0.13372338, 0.45232666, 0.15582252, 0.9621073 ,
       0.8151462 , 0.4068215 , 0.9565903 , 0.5532354 , 0.44936454,
       0.01469815, 0.86204493], dtype=float32)>

In [ ]:
t_sq.shape

TensorShape([12])

**One Hot Encoding**

In [ ]:
a_list = [1,2,3,4]
depth  = 5
tf.one_hot(a_list,depth)

<tf.Tensor: shape=(4, 5), dtype=float32, numpy=
array([[0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]], dtype=float32)>

In [ ]:
#custom values using On_value and off_values
tf.one_hot(a_list,depth,on_value="Y",off_value="N")

<tf.Tensor: shape=(4, 5), dtype=string, numpy=
array([[b'N', b'Y', b'N', b'N', b'N'],
       [b'N', b'N', b'Y', b'N', b'N'],
       [b'N', b'N', b'N', b'Y', b'N'],
       [b'N', b'N', b'N', b'N', b'Y']], dtype=object)>

**Math operation**
* squaring
* log
* square root

In [ ]:
S = tf.range(1,10)
S

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [ ]:
tf.square(S)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [ ]:
St=tf.cast(S,dtype=tf.float32) #(requires non-int values)
tf.sqrt(St)

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([1.       , 1.4142135, 1.7320508, 2.       , 2.2360678, 2.4494896,
       2.6457512, 2.828427 , 3.       ], dtype=float32)>

In [ ]:
#to find the log (finds the natural logarithms base(e) of the elements in the tensor)
tf.math.log(St)

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

In [ ]:
sig = tf.range(5,10) #sigmoid function
sig = tf.cast(sig,dtype=tf.float32)
tf.sigmoid(sig)

<tf.Tensor: shape=(5,), dtype=float32, numpy=
array([0.9933072 , 0.9975274 , 0.999089  , 0.99966466, 0.9998766 ],
      dtype=float32)>

For more methods follow : https://www.tensorflow.org/api_docs/python/tf/math/logical_and